name: tutorias_jic_v2
description: "Nueva versión del proyecto de tutorías para la JIC UTP Azuero."
publish_to: 'none'

environment:
  sdk: ^3.11.0  

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  google_fonts: ^8.0.2
  provider: ^6.1.5+1
  firebase_auth: ^6.3.0
