name: tutorias_jic_v2
description: "Nueva versión del proyecto de tutorías para la JIC UTP Azuero."
publish_to: 'none'

environment:
  sdk: ^3.11.0  

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  google_fonts: ^8.0.2
  provider: ^6.1.5+1
  firebase_auth: ^6.3.0
  fl_chart: ^1.2.0
  shared_preferences: ^2.5.5
  table_calendar: ^3.2.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_vecta.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_vecta.png"
  android_12:
    image: "assets/images/logo_vecta.png"
    color: "#FFFFFF"
