name: tutorias_jic_v2
description: "Nueva versión del proyecto de tutorías para la JIC UTP Azuero."
publish_to: 'none'

environment:
  sdk: ^3.11.0  

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.0
  # ... el resto de tus dependencias