// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKxWfapiFHqGsKyDqBZIpq3tGC118HMA',
    appId: '1:11231825446:web:be1b11b5eeddd8cb2fa0e7',
    messagingSenderId: '11231825446',
    projectId: 'tutorias-jic',
    authDomain: 'tutorias-jic.firebaseapp.com',
    databaseURL: 'https://tutorias-jic-default-rtdb.firebaseio.com',
    storageBucket: 'tutorias-jic.firebasestorage.app',
    measurementId: 'G-HVTRC1H41Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYa2tSI-Xm15ju4Lpi8cDnNZ0nI9RSyI',
    appId: '1:11231825446:android:ef0b155e738dc4fb2fa0e7',
    messagingSenderId: '11231825446',
    projectId: 'tutorias-jic',
    databaseURL: 'https://tutorias-jic-default-rtdb.firebaseio.com',
    storageBucket: 'tutorias-jic.firebasestorage.app',
  );
}
